export default {
  AUTH: "AUTH.SSO",
  HOME: "DASHBOARD",
  CONTENT: "MANAGEMENT.CONTENT",
  ALBUM: "MANAGEMENT.ALBUM",
  ALBUM_MEDIA: "MANAGEMENT.ALBUM.MEDIA",
  YOUTUBE: "MANAGEMENT.YOUTUBE.SYNC",
  YOUTUBE_AUTH: "MANAGEMENT.YOUTUBE.AUTH",
  PROFILE_EDIT: "MANAGEMENT.PROFILE.EDIT",
}